// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: account_mgr.proto

package accountmgr

import (
	"context"

	"github.com/starslipay/account_mgr/account_mgr_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	C2CTransferReq    = account_mgr_pb.C2CTransferReq
	C2CTransferRsp    = account_mgr_pb.C2CTransferRsp
	CreateAccountReq  = account_mgr_pb.CreateAccountReq
	CreateAccountRsp  = account_mgr_pb.CreateAccountRsp
	GetBalanceInfoReq = account_mgr_pb.GetBalanceInfoReq
	GetBalanceInfoRsp = account_mgr_pb.GetBalanceInfoRsp

	AccountMgr interface {
		CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error)
		GetBalanceInfo(ctx context.Context, in *GetBalanceInfoReq, opts ...grpc.CallOption) (*GetBalanceInfoRsp, error)
		C2CTransfer(ctx context.Context, in *C2CTransferReq, opts ...grpc.CallOption) (*C2CTransferRsp, error)
	}

	defaultAccountMgr struct {
		cli zrpc.Client
	}
)

func NewAccountMgr(cli zrpc.Client) AccountMgr {
	return &defaultAccountMgr{
		cli: cli,
	}
}

func (m *defaultAccountMgr) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.CreateAccount(ctx, in, opts...)
}

func (m *defaultAccountMgr) GetBalanceInfo(ctx context.Context, in *GetBalanceInfoReq, opts ...grpc.CallOption) (*GetBalanceInfoRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.GetBalanceInfo(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2CTransfer(ctx context.Context, in *C2CTransferReq, opts ...grpc.CallOption) (*C2CTransferRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2CTransfer(ctx, in, opts...)
}
