// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: account_mgr.proto

package accountmgr

import (
	"context"

	"github.com/starslipay/account_mgr/account_mgr_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Bank2CReq             = account_mgr_pb.Bank2CReq
	Bank2CRsp             = account_mgr_pb.Bank2CRsp
	C2BAsyncAccountReq    = account_mgr_pb.C2BAsyncAccountReq
	C2BAsyncAccountRsp    = account_mgr_pb.C2BAsyncAccountRsp
	C2BReq                = account_mgr_pb.C2BReq
	C2BRsp                = account_mgr_pb.C2BRsp
	C2BankReq             = account_mgr_pb.C2BankReq
	C2BankRsp             = account_mgr_pb.C2BankRsp
	C2CAsyncAccountReq    = account_mgr_pb.C2CAsyncAccountReq
	C2CAsyncAccountRsp    = account_mgr_pb.C2CAsyncAccountRsp
	C2CReq                = account_mgr_pb.C2CReq
	C2CRsp                = account_mgr_pb.C2CRsp
	CloseC2BBillReq       = account_mgr_pb.CloseC2BBillReq
	CloseC2BBillRsp       = account_mgr_pb.CloseC2BBillRsp
	CreateAccountReq      = account_mgr_pb.CreateAccountReq
	CreateAccountRsp      = account_mgr_pb.CreateAccountRsp
	GetC2CBillReq         = account_mgr_pb.GetC2CBillReq
	GetC2CBillRsp         = account_mgr_pb.GetC2CBillRsp
	GetUserBalanceInfoReq = account_mgr_pb.GetUserBalanceInfoReq
	GetUserBalanceInfoRsp = account_mgr_pb.GetUserBalanceInfoRsp
	GetUserFlowReq        = account_mgr_pb.GetUserFlowReq
	GetUserFlowRsp        = account_mgr_pb.GetUserFlowRsp
	QueryC2BBillReq       = account_mgr_pb.QueryC2BBillReq
	QueryC2BBillRsp       = account_mgr_pb.QueryC2BBillRsp
	UserFlow              = account_mgr_pb.UserFlow

	AccountMgr interface {
		CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error)
		GetUserBalanceInfo(ctx context.Context, in *GetUserBalanceInfoReq, opts ...grpc.CallOption) (*GetUserBalanceInfoRsp, error)
		GetUserFlow(ctx context.Context, in *GetUserFlowReq, opts ...grpc.CallOption) (*GetUserFlowRsp, error)
		GetC2CBill(ctx context.Context, in *GetC2CBillReq, opts ...grpc.CallOption) (*GetC2CBillRsp, error)
		Bank2C(ctx context.Context, in *Bank2CReq, opts ...grpc.CallOption) (*Bank2CRsp, error)
		C2Bank(ctx context.Context, in *C2BankReq, opts ...grpc.CallOption) (*C2BankRsp, error)
		C2CLocal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error)
		C2CFinal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error)
		C2CAsyncAccount(ctx context.Context, in *C2CAsyncAccountReq, opts ...grpc.CallOption) (*C2CAsyncAccountRsp, error)
		C2BFinal(ctx context.Context, in *C2BReq, opts ...grpc.CallOption) (*C2BRsp, error)
		C2BAsyncAccount(ctx context.Context, in *C2BAsyncAccountReq, opts ...grpc.CallOption) (*C2BAsyncAccountRsp, error)
		QueryC2BBill(ctx context.Context, in *QueryC2BBillReq, opts ...grpc.CallOption) (*QueryC2BBillRsp, error)
		CloseC2BBill(ctx context.Context, in *CloseC2BBillReq, opts ...grpc.CallOption) (*CloseC2BBillRsp, error)
	}

	defaultAccountMgr struct {
		cli zrpc.Client
	}
)

func NewAccountMgr(cli zrpc.Client) AccountMgr {
	return &defaultAccountMgr{
		cli: cli,
	}
}

func (m *defaultAccountMgr) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.CreateAccount(ctx, in, opts...)
}

func (m *defaultAccountMgr) GetUserBalanceInfo(ctx context.Context, in *GetUserBalanceInfoReq, opts ...grpc.CallOption) (*GetUserBalanceInfoRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.GetUserBalanceInfo(ctx, in, opts...)
}

func (m *defaultAccountMgr) GetUserFlow(ctx context.Context, in *GetUserFlowReq, opts ...grpc.CallOption) (*GetUserFlowRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.GetUserFlow(ctx, in, opts...)
}

func (m *defaultAccountMgr) GetC2CBill(ctx context.Context, in *GetC2CBillReq, opts ...grpc.CallOption) (*GetC2CBillRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.GetC2CBill(ctx, in, opts...)
}

func (m *defaultAccountMgr) Bank2C(ctx context.Context, in *Bank2CReq, opts ...grpc.CallOption) (*Bank2CRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.Bank2C(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2Bank(ctx context.Context, in *C2BankReq, opts ...grpc.CallOption) (*C2BankRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2Bank(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2CLocal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2CLocal(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2CFinal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2CFinal(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2CAsyncAccount(ctx context.Context, in *C2CAsyncAccountReq, opts ...grpc.CallOption) (*C2CAsyncAccountRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2CAsyncAccount(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2BFinal(ctx context.Context, in *C2BReq, opts ...grpc.CallOption) (*C2BRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2BFinal(ctx, in, opts...)
}

func (m *defaultAccountMgr) C2BAsyncAccount(ctx context.Context, in *C2BAsyncAccountReq, opts ...grpc.CallOption) (*C2BAsyncAccountRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.C2BAsyncAccount(ctx, in, opts...)
}

func (m *defaultAccountMgr) QueryC2BBill(ctx context.Context, in *QueryC2BBillReq, opts ...grpc.CallOption) (*QueryC2BBillRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.QueryC2BBill(ctx, in, opts...)
}

func (m *defaultAccountMgr) CloseC2BBill(ctx context.Context, in *CloseC2BBillReq, opts ...grpc.CallOption) (*CloseC2BBillRsp, error) {
	client := account_mgr_pb.NewAccountMgrClient(m.cli.Conn())
	return client.CloseC2BBill(ctx, in, opts...)
}
