// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: account_mgr.proto

package server

import (
	"context"

	"github.com/starslipay/account_mgr/account_mgr_pb"
	"github.com/starslipay/account_mgr/internal/logic"
	"github.com/starslipay/account_mgr/internal/svc"
)

type AccountMgrServer struct {
	svcCtx *svc.ServiceContext
	account_mgr_pb.UnimplementedAccountMgrServer
}

func NewAccountMgrServer(svcCtx *svc.ServiceContext) *AccountMgrServer {
	return &AccountMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountMgrServer) CreateAccount(ctx context.Context, in *account_mgr_pb.CreateAccountReq) (*account_mgr_pb.CreateAccountRsp, error) {
	l := logic.NewCreateAccountLogic(ctx, s.svcCtx)
	return l.CreateAccount(in)
}

func (s *AccountMgrServer) GetUserBalanceInfo(ctx context.Context, in *account_mgr_pb.GetUserBalanceInfoReq) (*account_mgr_pb.GetUserBalanceInfoRsp, error) {
	l := logic.NewGetUserBalanceInfoLogic(ctx, s.svcCtx)
	return l.GetUserBalanceInfo(in)
}

func (s *AccountMgrServer) C2CTransfer(ctx context.Context, in *account_mgr_pb.C2CTransferReq) (*account_mgr_pb.C2CTransferRsp, error) {
	l := logic.NewC2cTransferLogic(ctx, s.svcCtx)
	return l.C2CTransfer(in)
}
