// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: account_mgr.proto

package server

import (
	"context"

	"github.com/starslipay/account_mgr/account_mgr_pb"
	"github.com/starslipay/account_mgr/internal/logic"
	"github.com/starslipay/account_mgr/internal/svc"
)

type AccountMgrServer struct {
	svcCtx *svc.ServiceContext
	account_mgr_pb.UnimplementedAccountMgrServer
}

func NewAccountMgrServer(svcCtx *svc.ServiceContext) *AccountMgrServer {
	return &AccountMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountMgrServer) Bank2C(ctx context.Context, in *account_mgr_pb.Bank2CReq) (*account_mgr_pb.Bank2CRsp, error) {
	l := logic.NewBank2CLogic(ctx, s.svcCtx)
	return l.Bank2C(in)
}

func (s *AccountMgrServer) CreateAccount(ctx context.Context, in *account_mgr_pb.CreateAccountReq) (*account_mgr_pb.CreateAccountRsp, error) {
	l := logic.NewCreateAccountLogic(ctx, s.svcCtx)
	return l.CreateAccount(in)
}

func (s *AccountMgrServer) GetUserBalanceInfo(ctx context.Context, in *account_mgr_pb.GetUserBalanceInfoReq) (*account_mgr_pb.GetUserBalanceInfoRsp, error) {
	l := logic.NewGetUserBalanceInfoLogic(ctx, s.svcCtx)
	return l.GetUserBalanceInfo(in)
}

func (s *AccountMgrServer) C2C(ctx context.Context, in *account_mgr_pb.C2CReq) (*account_mgr_pb.C2CRsp, error) {
	l := logic.NewC2cLogic(ctx, s.svcCtx)
	return l.C2C(in)
}
