// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tBAccountFieldNames          = builder.RawFieldNames(&TBAccount{})
	tBAccountRows                = strings.Join(tBAccountFieldNames, ",")
	tBAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(tBAccountFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tBAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(tBAccountFieldNames, "`uid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tBAccountModel interface {
		Insert(ctx context.Context, data *TBAccount) (sql.Result, error)
		FindOne(ctx context.Context, uid int64) (*TBAccount, error)
		Update(ctx context.Context, data *TBAccount) error
		Delete(ctx context.Context, uid int64) error
	}

	defaultTBAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TBAccount struct {
		Uid        int64     `db:"uid"`      // 主键
		UserId     string    `db:"user_id"`  // 用户ID
		Balance    int64     `db:"balance"`  // 余额
		CurType    int64     `db:"cur_type"` // 货币类型
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTBAccountModel(conn sqlx.SqlConn) *defaultTBAccountModel {
	return &defaultTBAccountModel{
		conn:  conn,
		table: "`t_b_account`",
	}
}

func (m *defaultTBAccountModel) Delete(ctx context.Context, uid int64) error {
	query := fmt.Sprintf("delete from %s where `uid` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, uid)
	return err
}

func (m *defaultTBAccountModel) FindOne(ctx context.Context, uid int64) (*TBAccount, error) {
	query := fmt.Sprintf("select %s from %s where `uid` = ? limit 1", tBAccountRows, m.table)
	var resp TBAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBAccountModel) Insert(ctx context.Context, data *TBAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tBAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.Balance, data.CurType)
	return ret, err
}

func (m *defaultTBAccountModel) Update(ctx context.Context, data *TBAccount) error {
	query := fmt.Sprintf("update %s set %s where `uid` = ?", m.table, tBAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Balance, data.CurType, data.Uid)
	return err
}

func (m *defaultTBAccountModel) tableName() string {
	return m.table
}
