// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tBAccountFieldNames          = builder.RawFieldNames(&TBAccount{})
	tBAccountRows                = strings.Join(tBAccountFieldNames, ",")
	tBAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(tBAccountFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tBAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(tBAccountFieldNames, "`merchant_uid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tBAccountModel interface {
		Insert(ctx context.Context, data *TBAccount) (sql.Result, error)
		FindOne(ctx context.Context, merchantUid int64) (*TBAccount, error)
		Update(ctx context.Context, data *TBAccount) error
		Delete(ctx context.Context, merchantUid int64) error
	}

	defaultTBAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TBAccount struct {
		MerchantUid int64     `db:"merchant_uid"` // 商户UID
		MerchantId  string    `db:"merchant_id"`  // 商户ID
		Balance     int64     `db:"balance"`      // 余额
		CurType     int64     `db:"cur_type"`     // 货币类型
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newTBAccountModel(conn sqlx.SqlConn) *defaultTBAccountModel {
	return &defaultTBAccountModel{
		conn:  conn,
		table: "`t_b_account`",
	}
}

func (m *defaultTBAccountModel) Delete(ctx context.Context, merchantUid int64) error {
	query := fmt.Sprintf("delete from %s where `merchant_uid` = ?", m.table)
	ret, err := m.conn.ExecCtx(ctx, query, merchantUid)
	if err != nil {
		return err
	}
	return checkOneRowAffected(ret)
}

func (m *defaultTBAccountModel) FindOne(ctx context.Context, merchantUid int64) (*TBAccount, error) {
	query := fmt.Sprintf("select %s from %s where `merchant_uid` = ? limit 1", tBAccountRows, m.table)
	var resp TBAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, merchantUid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBAccountModel) Insert(ctx context.Context, data *TBAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tBAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MerchantUid, data.MerchantId, data.Balance, data.CurType)
	if err != nil {
		return ret, err
	}
	if err = checkOneRowAffected(ret); err != nil {
		return ret, err
	}
	return ret, nil
}

func (m *defaultTBAccountModel) Update(ctx context.Context, data *TBAccount) error {
	query := fmt.Sprintf("update %s set %s where `merchant_uid` = ?", m.table, tBAccountRowsWithPlaceHolder)
	ret, err := m.conn.ExecCtx(ctx, query, data.MerchantId, data.Balance, data.CurType, data.MerchantUid)
	if err != nil {
		return err
	}
	return checkOneRowAffected(ret)
}

func (m *defaultTBAccountModel) tableName() string {
	return m.table
}
