// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tBAccountLogFieldNames          = builder.RawFieldNames(&TBAccountLog{})
	tBAccountLogRows                = strings.Join(tBAccountLogFieldNames, ",")
	tBAccountLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tBAccountLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tBAccountLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tBAccountLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tBAccountLogModel interface {
		Insert(ctx context.Context, data *TBAccountLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TBAccountLog, error)
		FindOneByMerchantUidInoutTypeTransactionId(ctx context.Context, merchantUid int64, inoutType int64, transactionId string) (*TBAccountLog, error)
		Update(ctx context.Context, data *TBAccountLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTBAccountLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TBAccountLog struct {
		Id              int64     `db:"id"`               // 主键
		MerchantUid     int64     `db:"merchant_uid"`     // 商户UID
		MerchantId      string    `db:"merchant_id"`      // 商户ID
		CounterpartyId  string    `db:"counterparty_id"`  // 对方ID
		CounterpartyUid int64     `db:"counterparty_uid"` // 对方UID
		TransactionId   string    `db:"transaction_id"`   // 交易ID
		InoutType       int64     `db:"inout_type"`       // 出入金类型
		BizType         int64     `db:"biz_type"`         // 业务类型
		Balance         int64     `db:"balance"`          // 余额
		Amount          int64     `db:"amount"`           // 金额
		Desc            string    `db:"desc"`             // 描述
		CreateTime      time.Time `db:"create_time"`      // 创建时间
		UpdateTime      time.Time `db:"update_time"`      // 更新时间
	}
)

func newTBAccountLogModel(conn sqlx.SqlConn) *defaultTBAccountLogModel {
	return &defaultTBAccountLogModel{
		conn:  conn,
		table: "`t_b_account_log`",
	}
}

func (m *defaultTBAccountLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTBAccountLogModel) FindOne(ctx context.Context, id int64) (*TBAccountLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tBAccountLogRows, m.table)
	var resp TBAccountLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBAccountLogModel) FindOneByMerchantUidInoutTypeTransactionId(ctx context.Context, merchantUid int64, inoutType int64, transactionId string) (*TBAccountLog, error) {
	var resp TBAccountLog
	query := fmt.Sprintf("select %s from %s where `merchant_uid` = ? and `inout_type` = ? and `transaction_id` = ? limit 1", tBAccountLogRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, merchantUid, inoutType, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTBAccountLogModel) Insert(ctx context.Context, data *TBAccountLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tBAccountLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MerchantUid, data.MerchantId, data.CounterpartyId, data.CounterpartyUid, data.TransactionId, data.InoutType, data.BizType, data.Balance, data.Amount, data.Desc)
	return ret, err
}

func (m *defaultTBAccountLogModel) Update(ctx context.Context, newData *TBAccountLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tBAccountLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MerchantUid, newData.MerchantId, newData.CounterpartyId, newData.CounterpartyUid, newData.TransactionId, newData.InoutType, newData.BizType, newData.Balance, newData.Amount, newData.Desc, newData.Id)
	return err
}

func (m *defaultTBAccountLogModel) tableName() string {
	return m.table
}
