// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tC2bBillFieldNames          = builder.RawFieldNames(&TC2bBill{})
	tC2bBillRows                = strings.Join(tC2bBillFieldNames, ",")
	tC2bBillRowsExpectAutoSet   = strings.Join(stringx.Remove(tC2bBillFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tC2bBillRowsWithPlaceHolder = strings.Join(stringx.Remove(tC2bBillFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tC2bBillModel interface {
		Insert(ctx context.Context, data *TC2bBill) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TC2bBill, error)
		Update(ctx context.Context, data *TC2bBill) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTC2bBillModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TC2bBill struct {
		TransactionId string    `db:"transaction_id"` // 交易ID
		OutTradeNo    string    `db:"out_trade_no"`   // 商户订单号
		Uid           int64     `db:"uid"`            // 用户UID
		UserId        string    `db:"user_id"`        // 用户ID
		MerchantUid   int64     `db:"merchant_uid"`   // 商户UID
		MerchantId    string    `db:"merchant_id"`    // 商户ID
		Amount        int64     `db:"amount"`         // 金额
		State         int64     `db:"state"`          // 单状态
		BizType       int64     `db:"biz_type"`       // 业务类型
		Desc          string    `db:"desc"`           // 转账描述
		PayTime       time.Time `db:"pay_time"`       // 支付时间
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
	}
)

func newTC2bBillModel(conn sqlx.SqlConn) *defaultTC2bBillModel {
	return &defaultTC2bBillModel{
		conn:  conn,
		table: "`t_c2b_bill`",
	}
}

func (m *defaultTC2bBillModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	ret, err := m.conn.ExecCtx(ctx, query, transactionId)
	if err != nil {
		return err
	}
	return checkOneRowAffected(ret)
}

func (m *defaultTC2bBillModel) FindOne(ctx context.Context, transactionId string) (*TC2bBill, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tC2bBillRows, m.table)
	var resp TC2bBill
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTC2bBillModel) Insert(ctx context.Context, data *TC2bBill) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tC2bBillRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.OutTradeNo, data.Uid, data.UserId, data.MerchantUid, data.MerchantId, data.Amount, data.State, data.BizType, data.Desc, data.PayTime)
	if err != nil {
		return ret, err
	}
	if err = checkOneRowAffected(ret); err != nil {
		return ret, err
	}
	return ret, nil
}

func (m *defaultTC2bBillModel) Update(ctx context.Context, data *TC2bBill) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tC2bBillRowsWithPlaceHolder)
	ret, err := m.conn.ExecCtx(ctx, query, data.OutTradeNo, data.Uid, data.UserId, data.MerchantUid, data.MerchantId, data.Amount, data.State, data.BizType, data.Desc, data.PayTime, data.TransactionId)
	if err != nil {
		return err
	}
	return checkOneRowAffected(ret)
}

func (m *defaultTC2bBillModel) tableName() string {
	return m.table
}
