// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tC2bPendingTransferFieldNames          = builder.RawFieldNames(&TC2bPendingTransfer{})
	tC2bPendingTransferRows                = strings.Join(tC2bPendingTransferFieldNames, ",")
	tC2bPendingTransferRowsExpectAutoSet   = strings.Join(stringx.Remove(tC2bPendingTransferFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tC2bPendingTransferRowsWithPlaceHolder = strings.Join(stringx.Remove(tC2bPendingTransferFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tC2bPendingTransferModel interface {
		Insert(ctx context.Context, data *TC2bPendingTransfer) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TC2bPendingTransfer, error)
		Update(ctx context.Context, data *TC2bPendingTransfer) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTC2bPendingTransferModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TC2bPendingTransfer struct {
		TransactionId string    `db:"transaction_id"` // 交易ID
		Uid           int64     `db:"uid"`            // 用户UID
		UserId        string    `db:"user_id"`        // 用户ID
		MerchantUid   int64     `db:"merchant_uid"`   // 商户UID
		MerchantId    string    `db:"merchant_id"`    // 商户ID
		Amount        int64     `db:"amount"`         // 金额
		State         int64     `db:"state"`          // 状态
		Desc          string    `db:"desc"`           // 转账描述
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
	}
)

func newTC2bPendingTransferModel(conn sqlx.SqlConn) *defaultTC2bPendingTransferModel {
	return &defaultTC2bPendingTransferModel{
		conn:  conn,
		table: "`t_c2b_pending_transfer`",
	}
}

func (m *defaultTC2bPendingTransferModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTC2bPendingTransferModel) FindOne(ctx context.Context, transactionId string) (*TC2bPendingTransfer, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tC2bPendingTransferRows, m.table)
	var resp TC2bPendingTransfer
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTC2bPendingTransferModel) Insert(ctx context.Context, data *TC2bPendingTransfer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tC2bPendingTransferRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.Uid, data.UserId, data.MerchantUid, data.MerchantId, data.Amount, data.State, data.Desc)
	return ret, err
}

func (m *defaultTC2bPendingTransferModel) Update(ctx context.Context, data *TC2bPendingTransfer) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tC2bPendingTransferRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.MerchantUid, data.MerchantId, data.Amount, data.State, data.Desc, data.TransactionId)
	return err
}

func (m *defaultTC2bPendingTransferModel) tableName() string {
	return m.table
}
