// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tC2cBillFieldNames          = builder.RawFieldNames(&TC2cBill{})
	tC2cBillRows                = strings.Join(tC2cBillFieldNames, ",")
	tC2cBillRowsExpectAutoSet   = strings.Join(stringx.Remove(tC2cBillFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tC2cBillRowsWithPlaceHolder = strings.Join(stringx.Remove(tC2cBillFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tC2cBillModel interface {
		Insert(ctx context.Context, data *TC2cBill) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TC2cBill, error)
		Update(ctx context.Context, data *TC2cBill) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTC2cBillModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TC2cBill struct {
		TransactionId string    `db:"transaction_id"` // 订单ID
		BuyerUid      int64     `db:"buyer_uid"`      // 买家用户UID
		SellerUid     int64     `db:"seller_uid"`     // 卖家用户UID
		BuyerUserId   string    `db:"buyer_user_id"`  // 买家用户ID
		SellerUserId  string    `db:"seller_user_id"` // 卖家用户ID
		Amount        int64     `db:"amount"`         // 金额
		State         int64     `db:"state"`          // 单状态
		BizType       int64     `db:"biz_type"`       // 业务类型
		Desc          string    `db:"desc"`           // 转账描述
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
	}
)

func newTC2cBillModel(conn sqlx.SqlConn) *defaultTC2cBillModel {
	return &defaultTC2cBillModel{
		conn:  conn,
		table: "`t_c2c_bill`",
	}
}

func (m *defaultTC2cBillModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTC2cBillModel) FindOne(ctx context.Context, transactionId string) (*TC2cBill, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tC2cBillRows, m.table)
	var resp TC2cBill
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTC2cBillModel) Insert(ctx context.Context, data *TC2cBill) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tC2cBillRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.State, data.BizType, data.Desc)
	return ret, err
}

func (m *defaultTC2cBillModel) Update(ctx context.Context, data *TC2cBill) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tC2cBillRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.State, data.BizType, data.Desc, data.TransactionId)
	return err
}

func (m *defaultTC2cBillModel) tableName() string {
	return m.table
}
