// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tC2cPendingTransferFieldNames          = builder.RawFieldNames(&TC2cPendingTransfer{})
	tC2cPendingTransferRows                = strings.Join(tC2cPendingTransferFieldNames, ",")
	tC2cPendingTransferRowsExpectAutoSet   = strings.Join(stringx.Remove(tC2cPendingTransferFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tC2cPendingTransferRowsWithPlaceHolder = strings.Join(stringx.Remove(tC2cPendingTransferFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tC2cPendingTransferModel interface {
		Insert(ctx context.Context, data *TC2cPendingTransfer) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TC2cPendingTransfer, error)
		Update(ctx context.Context, data *TC2cPendingTransfer) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTC2cPendingTransferModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TC2cPendingTransfer struct {
		TransactionId string    `db:"transaction_id"` // 交易ID
		BuyerUid      int64     `db:"buyer_uid"`      // 买家用户UID
		SellerUid     int64     `db:"seller_uid"`     // 卖家用户UID
		BuyerUserId   string    `db:"buyer_user_id"`  // 买家用户ID
		SellerUserId  string    `db:"seller_user_id"` // 卖家用户ID
		Amount        int64     `db:"amount"`         // 金额
		State         int64     `db:"state"`          // 状态
		Desc          string    `db:"desc"`           // 转账描述
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
	}
)

func newTC2cPendingTransferModel(conn sqlx.SqlConn) *defaultTC2cPendingTransferModel {
	return &defaultTC2cPendingTransferModel{
		conn:  conn,
		table: "`t_c2c_pending_transfer`",
	}
}

func (m *defaultTC2cPendingTransferModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	ret, err := m.conn.ExecCtx(ctx, query, transactionId)
	if err != nil {
		return err
	}
	return checkOneRowAffected(ret)
}

func (m *defaultTC2cPendingTransferModel) FindOne(ctx context.Context, transactionId string) (*TC2cPendingTransfer, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tC2cPendingTransferRows, m.table)
	var resp TC2cPendingTransfer
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTC2cPendingTransferModel) Insert(ctx context.Context, data *TC2cPendingTransfer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tC2cPendingTransferRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.State, data.Desc)
	if err != nil {
		return ret, err
	}
	if err = checkOneRowAffected(ret); err != nil {
		return ret, err
	}
	return ret, nil
}

func (m *defaultTC2cPendingTransferModel) Update(ctx context.Context, data *TC2cPendingTransfer) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tC2cPendingTransferRowsWithPlaceHolder)
	ret, err := m.conn.ExecCtx(ctx, query, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.State, data.Desc, data.TransactionId)
	if err != nil {
		return err
	}
	return checkOneRowAffected(ret)
}

func (m *defaultTC2cPendingTransferModel) tableName() string {
	return m.table
}
