// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tC2cTransferOrderFieldNames          = builder.RawFieldNames(&TC2cTransferOrder{})
	tC2cTransferOrderRows                = strings.Join(tC2cTransferOrderFieldNames, ",")
	tC2cTransferOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(tC2cTransferOrderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tC2cTransferOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(tC2cTransferOrderFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tC2cTransferOrderModel interface {
		Insert(ctx context.Context, data *TC2cTransferOrder) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TC2cTransferOrder, error)
		Update(ctx context.Context, data *TC2cTransferOrder) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTC2cTransferOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TC2cTransferOrder struct {
		TransactionId string    `db:"transaction_id"` // 订单ID
		BuyerUid      int64     `db:"buyer_uid"`      // 买家用户UID
		SellerUid     int64     `db:"seller_uid"`     // 卖家用户UID
		BuyerUserId   string    `db:"buyer_user_id"`  // 买家用户ID
		SellerUserId  string    `db:"seller_user_id"` // 卖家用户ID
		Amount        int64     `db:"amount"`         // 金额
		BizType       int64     `db:"biz_type"`       // 业务类型
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
	}
)

func newTC2cTransferOrderModel(conn sqlx.SqlConn) *defaultTC2cTransferOrderModel {
	return &defaultTC2cTransferOrderModel{
		conn:  conn,
		table: "`t_c2c_transfer_order`",
	}
}

func (m *defaultTC2cTransferOrderModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTC2cTransferOrderModel) FindOne(ctx context.Context, transactionId string) (*TC2cTransferOrder, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tC2cTransferOrderRows, m.table)
	var resp TC2cTransferOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTC2cTransferOrderModel) Insert(ctx context.Context, data *TC2cTransferOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tC2cTransferOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.BizType)
	return ret, err
}

func (m *defaultTC2cTransferOrderModel) Update(ctx context.Context, data *TC2cTransferOrder) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tC2cTransferOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.BizType, data.TransactionId)
	return err
}

func (m *defaultTC2cTransferOrderModel) tableName() string {
	return m.table
}
