// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tCAccountLogFieldNames          = builder.RawFieldNames(&TCAccountLog{})
	tCAccountLogRows                = strings.Join(tCAccountLogFieldNames, ",")
	tCAccountLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tCAccountLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tCAccountLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tCAccountLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tCAccountLogModel interface {
		Insert(ctx context.Context, data *TCAccountLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TCAccountLog, error)
		FindOneByUidInoutTypeTransactionId(ctx context.Context, uid int64, inoutType int64, transactionId string) (*TCAccountLog, error)
		Update(ctx context.Context, data *TCAccountLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTCAccountLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TCAccountLog struct {
		Id                 int64     `db:"id"`                   // 主键
		Uid                int64     `db:"uid"`                  // 用户UID
		UserId             string    `db:"user_id"`              // 用户ID
		CounterpartyUserId string    `db:"counterparty_user_id"` // 对方用户ID
		CounterpartyUid    int64     `db:"counterparty_uid"`     // 对方用户UID
		TransactionId      string    `db:"transaction_id"`       // 交易ID
		InoutType          int64     `db:"inout_type"`           // 出入金类型
		BizType            int64     `db:"biz_type"`             // 业务类型
		Balance            int64     `db:"balance"`              // 余额
		Amount             int64     `db:"amount"`               // 金额
		CreateTime         time.Time `db:"create_time"`
		UpdateTime         time.Time `db:"update_time"`
	}
)

func newTCAccountLogModel(conn sqlx.SqlConn) *defaultTCAccountLogModel {
	return &defaultTCAccountLogModel{
		conn:  conn,
		table: "`t_c_account_log`",
	}
}

func (m *defaultTCAccountLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTCAccountLogModel) FindOne(ctx context.Context, id int64) (*TCAccountLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tCAccountLogRows, m.table)
	var resp TCAccountLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTCAccountLogModel) FindOneByUidInoutTypeTransactionId(ctx context.Context, uid int64, inoutType int64, transactionId string) (*TCAccountLog, error) {
	var resp TCAccountLog
	query := fmt.Sprintf("select %s from %s where `uid` = ? and `inout_type` = ? and `transaction_id` = ? limit 1", tCAccountLogRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid, inoutType, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTCAccountLogModel) Insert(ctx context.Context, data *TCAccountLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tCAccountLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.CounterpartyUserId, data.CounterpartyUid, data.TransactionId, data.InoutType, data.BizType, data.Balance, data.Amount)
	return ret, err
}

func (m *defaultTCAccountLogModel) Update(ctx context.Context, newData *TCAccountLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tCAccountLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Uid, newData.UserId, newData.CounterpartyUserId, newData.CounterpartyUid, newData.TransactionId, newData.InoutType, newData.BizType, newData.Balance, newData.Amount, newData.Id)
	return err
}

func (m *defaultTCAccountLogModel) tableName() string {
	return m.table
}
