// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tCAccountFieldNames          = builder.RawFieldNames(&TCAccount{})
	tCAccountRows                = strings.Join(tCAccountFieldNames, ",")
	tCAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(tCAccountFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tCAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(tCAccountFieldNames, "`uid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tCAccountModel interface {
		Insert(ctx context.Context, data *TCAccount) (sql.Result, error)
		FindOne(ctx context.Context, uid int64) (*TCAccount, error)
		Update(ctx context.Context, data *TCAccount) error
		Delete(ctx context.Context, uid int64) error
	}

	defaultTCAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TCAccount struct {
		Uid        int64     `db:"uid"`      // 主键
		UserId     string    `db:"user_id"`  // 用户ID
		Balance    int64     `db:"balance"`  // 余额
		CurType    int64     `db:"cur_type"` // 货币类型
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTCAccountModel(conn sqlx.SqlConn) *defaultTCAccountModel {
	return &defaultTCAccountModel{
		conn:  conn,
		table: "`t_c_account`",
	}
}

func (m *defaultTCAccountModel) Delete(ctx context.Context, uid int64) error {
	query := fmt.Sprintf("delete from %s where `uid` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, uid)
	return err
}

func (m *defaultTCAccountModel) FindOne(ctx context.Context, uid int64) (*TCAccount, error) {
	query := fmt.Sprintf("select %s from %s where `uid` = ? limit 1", tCAccountRows, m.table)
	var resp TCAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTCAccountModel) Insert(ctx context.Context, data *TCAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tCAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.Balance, data.CurType)
	return ret, err
}

func (m *defaultTCAccountModel) Update(ctx context.Context, data *TCAccount) error {
	query := fmt.Sprintf("update %s set %s where `uid` = ?", m.table, tCAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Balance, data.CurType, data.Uid)
	return err
}

func (m *defaultTCAccountModel) tableName() string {
	return m.table
}
