// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLocalMessageFieldNames          = builder.RawFieldNames(&TLocalMessage{})
	tLocalMessageRows                = strings.Join(tLocalMessageFieldNames, ",")
	tLocalMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(tLocalMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLocalMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(tLocalMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLocalMessageModel interface {
		Insert(ctx context.Context, data *TLocalMessage) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLocalMessage, error)
		FindOneByTransactionId(ctx context.Context, transactionId string) (*TLocalMessage, error)
		Update(ctx context.Context, data *TLocalMessage) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLocalMessageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLocalMessage struct {
		Id            int64     `db:"id"`             // 主键
		TransactionId string    `db:"transaction_id"` // 交易ID
		MsgType       int64     `db:"msg_type"`       // 消息类型
		Topic         string    `db:"topic"`          // 消息主题
		Partition     int64     `db:"partition"`      // 消息分区
		Key           string    `db:"key"`            // 消息key
		Body          string    `db:"body"`           // 消息体(JSON)
		State         int64     `db:"state"`          // 消息状态
		SendCount     int64     `db:"send_count"`     // 消息发送次数
		MaxSendCount  int64     `db:"max_send_count"` // 消息最大重试次数
		NextSendTime  time.Time `db:"next_send_time"` // 下次发送时间
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
	}
)

func newTLocalMessageModel(conn sqlx.SqlConn) *defaultTLocalMessageModel {
	return &defaultTLocalMessageModel{
		conn:  conn,
		table: "`t_local_message`",
	}
}

func (m *defaultTLocalMessageModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLocalMessageModel) FindOne(ctx context.Context, id int64) (*TLocalMessage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLocalMessageRows, m.table)
	var resp TLocalMessage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLocalMessageModel) FindOneByTransactionId(ctx context.Context, transactionId string) (*TLocalMessage, error) {
	var resp TLocalMessage
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tLocalMessageRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLocalMessageModel) Insert(ctx context.Context, data *TLocalMessage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tLocalMessageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.MsgType, data.Topic, data.Partition, data.Key, data.Body, data.State, data.SendCount, data.MaxSendCount, data.NextSendTime)
	return ret, err
}

func (m *defaultTLocalMessageModel) Update(ctx context.Context, newData *TLocalMessage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLocalMessageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TransactionId, newData.MsgType, newData.Topic, newData.Partition, newData.Key, newData.Body, newData.State, newData.SendCount, newData.MaxSendCount, newData.NextSendTime, newData.Id)
	return err
}

func (m *defaultTLocalMessageModel) tableName() string {
	return m.table
}
