// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tPendingC2cTransferFieldNames          = builder.RawFieldNames(&TPendingC2cTransfer{})
	tPendingC2cTransferRows                = strings.Join(tPendingC2cTransferFieldNames, ",")
	tPendingC2cTransferRowsExpectAutoSet   = strings.Join(stringx.Remove(tPendingC2cTransferFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tPendingC2cTransferRowsWithPlaceHolder = strings.Join(stringx.Remove(tPendingC2cTransferFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tPendingC2cTransferModel interface {
		Insert(ctx context.Context, data *TPendingC2cTransfer) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TPendingC2cTransfer, error)
		Update(ctx context.Context, data *TPendingC2cTransfer) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTPendingC2cTransferModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TPendingC2cTransfer struct {
		TransactionId string    `db:"transaction_id"` // 交易ID
		BuyerUid      int64     `db:"buyer_uid"`      // 买家用户UID
		SellerUid     int64     `db:"seller_uid"`     // 卖家用户UID
		BuyerUserId   string    `db:"buyer_user_id"`  // 买家用户ID
		SellerUserId  string    `db:"seller_user_id"` // 卖家用户ID
		Amount        int64     `db:"amount"`         // 金额
		State         int64     `db:"state"`          // 状态
		BizType       int64     `db:"biz_type"`       // 业务类型
		Desc          string    `db:"desc"`           // 转账描述
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
	}
)

func newTPendingC2cTransferModel(conn sqlx.SqlConn) *defaultTPendingC2cTransferModel {
	return &defaultTPendingC2cTransferModel{
		conn:  conn,
		table: "`t_pending_c2c_transfer`",
	}
}

func (m *defaultTPendingC2cTransferModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTPendingC2cTransferModel) FindOne(ctx context.Context, transactionId string) (*TPendingC2cTransfer, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tPendingC2cTransferRows, m.table)
	var resp TPendingC2cTransfer
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPendingC2cTransferModel) Insert(ctx context.Context, data *TPendingC2cTransfer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tPendingC2cTransferRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.State, data.BizType, data.Desc)
	return ret, err
}

func (m *defaultTPendingC2cTransferModel) Update(ctx context.Context, data *TPendingC2cTransfer) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tPendingC2cTransferRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BuyerUid, data.SellerUid, data.BuyerUserId, data.SellerUserId, data.Amount, data.State, data.BizType, data.Desc, data.TransactionId)
	return err
}

func (m *defaultTPendingC2cTransferModel) tableName() string {
	return m.table
}
