// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tSaveBillFieldNames          = builder.RawFieldNames(&TSaveBill{})
	tSaveBillRows                = strings.Join(tSaveBillFieldNames, ",")
	tSaveBillRowsExpectAutoSet   = strings.Join(stringx.Remove(tSaveBillFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tSaveBillRowsWithPlaceHolder = strings.Join(stringx.Remove(tSaveBillFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tSaveBillModel interface {
		Insert(ctx context.Context, data *TSaveBill) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TSaveBill, error)
		Update(ctx context.Context, data *TSaveBill) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTSaveBillModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TSaveBill struct {
		TransactionId string    `db:"transaction_id"` // 订单ID
		Uid           int64     `db:"uid"`            // 用户UID
		UserId        string    `db:"user_id"`        // 用户ID
		BankType      string    `db:"bank_type"`      // 银行类型
		Amount        int64     `db:"amount"`         // 金额
		State         int64     `db:"state"`          // 单状态
		Desc          string    `db:"desc"`           // 充值描述
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
	}
)

func newTSaveBillModel(conn sqlx.SqlConn) *defaultTSaveBillModel {
	return &defaultTSaveBillModel{
		conn:  conn,
		table: "`t_save_bill`",
	}
}

func (m *defaultTSaveBillModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTSaveBillModel) FindOne(ctx context.Context, transactionId string) (*TSaveBill, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tSaveBillRows, m.table)
	var resp TSaveBill
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSaveBillModel) Insert(ctx context.Context, data *TSaveBill) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tSaveBillRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.Uid, data.UserId, data.BankType, data.Amount, data.State, data.Desc)
	return ret, err
}

func (m *defaultTSaveBillModel) Update(ctx context.Context, data *TSaveBill) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tSaveBillRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.BankType, data.Amount, data.State, data.Desc, data.TransactionId)
	return err
}

func (m *defaultTSaveBillModel) tableName() string {
	return m.table
}
