// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: account_mgr.proto

package account_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建账户Req
type CreateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurType       int32                  `protobuf:"varint,3,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	mi := &file_account_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAccountReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

// 创建账户Rsp
type CreateAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRepeat      bool                   `protobuf:"varint,3,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRsp) Reset() {
	*x = CreateAccountRsp{}
	mi := &file_account_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRsp) ProtoMessage() {}

func (x *CreateAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRsp.ProtoReflect.Descriptor instead.
func (*CreateAccountRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAccountRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRsp) GetIsRepeat() bool {
	if x != nil {
		return x.IsRepeat
	}
	return false
}

// 获取账户余额Req
type GetBalanceInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	QryMode       int32                  `protobuf:"varint,2,opt,name=qry_mode,json=qryMode,proto3" json:"qry_mode,omitempty"` // 1-查从库 2-查主库
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceInfoReq) Reset() {
	*x = GetBalanceInfoReq{}
	mi := &file_account_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceInfoReq) ProtoMessage() {}

func (x *GetBalanceInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceInfoReq.ProtoReflect.Descriptor instead.
func (*GetBalanceInfoReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceInfoReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetBalanceInfoReq) GetQryMode() int32 {
	if x != nil {
		return x.QryMode
	}
	return 0
}

// 获取账户余额Rsp
type GetBalanceInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CurType       int32                  `protobuf:"varint,4,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceInfoRsp) Reset() {
	*x = GetBalanceInfoRsp{}
	mi := &file_account_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceInfoRsp) ProtoMessage() {}

func (x *GetBalanceInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceInfoRsp.ProtoReflect.Descriptor instead.
func (*GetBalanceInfoRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceInfoRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetBalanceInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceInfoRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceInfoRsp) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

// 转账Req
type C2CTransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	BuyerUid      int64                  `protobuf:"varint,2,opt,name=buyer_uid,json=buyerUid,proto3" json:"buyer_uid,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUid     int64                  `protobuf:"varint,4,opt,name=seller_uid,json=sellerUid,proto3" json:"seller_uid,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,5,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	CurType       int32                  `protobuf:"varint,7,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	TransferDesc  string                 `protobuf:"bytes,8,opt,name=transfer_desc,json=transferDesc,proto3" json:"transfer_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferReq) Reset() {
	*x = C2CTransferReq{}
	mi := &file_account_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferReq) ProtoMessage() {}

func (x *C2CTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferReq.ProtoReflect.Descriptor instead.
func (*C2CTransferReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *C2CTransferReq) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *C2CTransferReq) GetBuyerUid() int64 {
	if x != nil {
		return x.BuyerUid
	}
	return 0
}

func (x *C2CTransferReq) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferReq) GetSellerUid() int64 {
	if x != nil {
		return x.SellerUid
	}
	return 0
}

func (x *C2CTransferReq) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CTransferReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2CTransferReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

func (x *C2CTransferReq) GetTransferDesc() string {
	if x != nil {
		return x.TransferDesc
	}
	return ""
}

// 转账Rsp
type C2CTransferRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	BuyerUid      int64                  `protobuf:"varint,2,opt,name=buyer_uid,json=buyerUid,proto3" json:"buyer_uid,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUid     int64                  `protobuf:"varint,4,opt,name=seller_uid,json=sellerUid,proto3" json:"seller_uid,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,5,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	TransferTime  string                 `protobuf:"bytes,6,opt,name=transfer_time,json=transferTime,proto3" json:"transfer_time,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,7,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CTransferRsp) Reset() {
	*x = C2CTransferRsp{}
	mi := &file_account_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CTransferRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CTransferRsp) ProtoMessage() {}

func (x *C2CTransferRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CTransferRsp.ProtoReflect.Descriptor instead.
func (*C2CTransferRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *C2CTransferRsp) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *C2CTransferRsp) GetBuyerUid() int64 {
	if x != nil {
		return x.BuyerUid
	}
	return 0
}

func (x *C2CTransferRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CTransferRsp) GetSellerUid() int64 {
	if x != nil {
		return x.SellerUid
	}
	return 0
}

func (x *C2CTransferRsp) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CTransferRsp) GetTransferTime() string {
	if x != nil {
		return x.TransferTime
	}
	return ""
}

func (x *C2CTransferRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

var File_account_mgr_proto protoreflect.FileDescriptor

const file_account_mgr_proto_rawDesc = "" +
	"\n" +
	"\x11account_mgr.proto\x12\vaccount_mgr\"X\n" +
	"\x10CreateAccountReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bcur_type\x18\x03 \x01(\x05R\acurType\"Z\n" +
	"\x10CreateAccountRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_repeat\x18\x03 \x01(\bR\bisRepeat\"@\n" +
	"\x11GetBalanceInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\bqry_mode\x18\x02 \x01(\x05R\aqryMode\"s\n" +
	"\x11GetBalanceInfoRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x19\n" +
	"\bcur_type\x18\x04 \x01(\x05R\acurType\"\x8f\x02\n" +
	"\x0eC2cTransferReq\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tbuyer_uid\x18\x02 \x01(\x03R\bbuyerUid\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12\x1d\n" +
	"\n" +
	"seller_uid\x18\x04 \x01(\x03R\tsellerUid\x12$\n" +
	"\x0eseller_user_id\x18\x05 \x01(\tR\fsellerUserId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x19\n" +
	"\bcur_type\x18\a \x01(\x05R\acurType\x12#\n" +
	"\rtransfer_desc\x18\b \x01(\tR\ftransferDesc\"\xf9\x01\n" +
	"\x0eC2cTransferRsp\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tbuyer_uid\x18\x02 \x01(\x03R\bbuyerUid\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12\x1d\n" +
	"\n" +
	"seller_uid\x18\x04 \x01(\x03R\tsellerUid\x12$\n" +
	"\x0eseller_user_id\x18\x05 \x01(\tR\fsellerUserId\x12#\n" +
	"\rtransfer_time\x18\x06 \x01(\tR\ftransferTime\x12\x1b\n" +
	"\tis_repeat\x18\a \x01(\x05R\bisRepeat2\xf6\x01\n" +
	"\n" +
	"AccountMgr\x12M\n" +
	"\rCreateAccount\x12\x1d.account_mgr.CreateAccountReq\x1a\x1d.account_mgr.CreateAccountRsp\x12P\n" +
	"\x0eGetBalanceInfo\x12\x1e.account_mgr.GetBalanceInfoReq\x1a\x1e.account_mgr.GetBalanceInfoRsp\x12G\n" +
	"\vC2cTransfer\x12\x1b.account_mgr.C2cTransferReq\x1a\x1b.account_mgr.C2cTransferRspB\x12Z\x10./account_mgr_pbb\x06proto3"

var (
	file_account_mgr_proto_rawDescOnce sync.Once
	file_account_mgr_proto_rawDescData []byte
)

func file_account_mgr_proto_rawDescGZIP() []byte {
	file_account_mgr_proto_rawDescOnce.Do(func() {
		file_account_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_mgr_proto_rawDesc), len(file_account_mgr_proto_rawDesc)))
	})
	return file_account_mgr_proto_rawDescData
}

var file_account_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_account_mgr_proto_goTypes = []any{
	(*CreateAccountReq)(nil),  // 0: account_mgr.CreateAccountReq
	(*CreateAccountRsp)(nil),  // 1: account_mgr.CreateAccountRsp
	(*GetBalanceInfoReq)(nil), // 2: account_mgr.GetBalanceInfoReq
	(*GetBalanceInfoRsp)(nil), // 3: account_mgr.GetBalanceInfoRsp
	(*C2CTransferReq)(nil),    // 4: account_mgr.C2cTransferReq
	(*C2CTransferRsp)(nil),    // 5: account_mgr.C2cTransferRsp
}
var file_account_mgr_proto_depIdxs = []int32{
	0, // 0: account_mgr.AccountMgr.CreateAccount:input_type -> account_mgr.CreateAccountReq
	2, // 1: account_mgr.AccountMgr.GetBalanceInfo:input_type -> account_mgr.GetBalanceInfoReq
	4, // 2: account_mgr.AccountMgr.C2cTransfer:input_type -> account_mgr.C2cTransferReq
	1, // 3: account_mgr.AccountMgr.CreateAccount:output_type -> account_mgr.CreateAccountRsp
	3, // 4: account_mgr.AccountMgr.GetBalanceInfo:output_type -> account_mgr.GetBalanceInfoRsp
	5, // 5: account_mgr.AccountMgr.C2cTransfer:output_type -> account_mgr.C2cTransferRsp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_mgr_proto_init() }
func file_account_mgr_proto_init() {
	if File_account_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_mgr_proto_rawDesc), len(file_account_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_mgr_proto_goTypes,
		DependencyIndexes: file_account_mgr_proto_depIdxs,
		MessageInfos:      file_account_mgr_proto_msgTypes,
	}.Build()
	File_account_mgr_proto = out.File
	file_account_mgr_proto_goTypes = nil
	file_account_mgr_proto_depIdxs = nil
}
