// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: account_mgr.proto

package account_mgr_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountMgr_Bank2C_FullMethodName             = "/account_mgr.AccountMgr/Bank2C"
	AccountMgr_CreateAccount_FullMethodName      = "/account_mgr.AccountMgr/CreateAccount"
	AccountMgr_GetUserBalanceInfo_FullMethodName = "/account_mgr.AccountMgr/GetUserBalanceInfo"
	AccountMgr_C2CLocal_FullMethodName           = "/account_mgr.AccountMgr/C2cLocal"
	AccountMgr_C2CStrong_FullMethodName          = "/account_mgr.AccountMgr/C2cStrong"
	AccountMgr_C2CFinal_FullMethodName           = "/account_mgr.AccountMgr/C2cFinal"
)

// AccountMgrClient is the client API for AccountMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountMgrClient interface {
	Bank2C(ctx context.Context, in *Bank2CReq, opts ...grpc.CallOption) (*Bank2CRsp, error)
	CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error)
	GetUserBalanceInfo(ctx context.Context, in *GetUserBalanceInfoReq, opts ...grpc.CallOption) (*GetUserBalanceInfoRsp, error)
	C2CLocal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error)
	C2CStrong(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error)
	C2CFinal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error)
}

type accountMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountMgrClient(cc grpc.ClientConnInterface) AccountMgrClient {
	return &accountMgrClient{cc}
}

func (c *accountMgrClient) Bank2C(ctx context.Context, in *Bank2CReq, opts ...grpc.CallOption) (*Bank2CRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bank2CRsp)
	err := c.cc.Invoke(ctx, AccountMgr_Bank2C_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountRsp)
	err := c.cc.Invoke(ctx, AccountMgr_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) GetUserBalanceInfo(ctx context.Context, in *GetUserBalanceInfoReq, opts ...grpc.CallOption) (*GetUserBalanceInfoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBalanceInfoRsp)
	err := c.cc.Invoke(ctx, AccountMgr_GetUserBalanceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) C2CLocal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2CRsp)
	err := c.cc.Invoke(ctx, AccountMgr_C2CLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) C2CStrong(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2CRsp)
	err := c.cc.Invoke(ctx, AccountMgr_C2CStrong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) C2CFinal(ctx context.Context, in *C2CReq, opts ...grpc.CallOption) (*C2CRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2CRsp)
	err := c.cc.Invoke(ctx, AccountMgr_C2CFinal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountMgrServer is the server API for AccountMgr service.
// All implementations must embed UnimplementedAccountMgrServer
// for forward compatibility.
type AccountMgrServer interface {
	Bank2C(context.Context, *Bank2CReq) (*Bank2CRsp, error)
	CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountRsp, error)
	GetUserBalanceInfo(context.Context, *GetUserBalanceInfoReq) (*GetUserBalanceInfoRsp, error)
	C2CLocal(context.Context, *C2CReq) (*C2CRsp, error)
	C2CStrong(context.Context, *C2CReq) (*C2CRsp, error)
	C2CFinal(context.Context, *C2CReq) (*C2CRsp, error)
	mustEmbedUnimplementedAccountMgrServer()
}

// UnimplementedAccountMgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountMgrServer struct{}

func (UnimplementedAccountMgrServer) Bank2C(context.Context, *Bank2CReq) (*Bank2CRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Bank2C not implemented")
}
func (UnimplementedAccountMgrServer) CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountMgrServer) GetUserBalanceInfo(context.Context, *GetUserBalanceInfoReq) (*GetUserBalanceInfoRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBalanceInfo not implemented")
}
func (UnimplementedAccountMgrServer) C2CLocal(context.Context, *C2CReq) (*C2CRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2CLocal not implemented")
}
func (UnimplementedAccountMgrServer) C2CStrong(context.Context, *C2CReq) (*C2CRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2CStrong not implemented")
}
func (UnimplementedAccountMgrServer) C2CFinal(context.Context, *C2CReq) (*C2CRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2CFinal not implemented")
}
func (UnimplementedAccountMgrServer) mustEmbedUnimplementedAccountMgrServer() {}
func (UnimplementedAccountMgrServer) testEmbeddedByValue()                    {}

// UnsafeAccountMgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountMgrServer will
// result in compilation errors.
type UnsafeAccountMgrServer interface {
	mustEmbedUnimplementedAccountMgrServer()
}

func RegisterAccountMgrServer(s grpc.ServiceRegistrar, srv AccountMgrServer) {
	// If the following call panics, it indicates UnimplementedAccountMgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountMgr_ServiceDesc, srv)
}

func _AccountMgr_Bank2C_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bank2CReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).Bank2C(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_Bank2C_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).Bank2C(ctx, req.(*Bank2CReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).CreateAccount(ctx, req.(*CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_GetUserBalanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBalanceInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).GetUserBalanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_GetUserBalanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).GetUserBalanceInfo(ctx, req.(*GetUserBalanceInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_C2CLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).C2CLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_C2CLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).C2CLocal(ctx, req.(*C2CReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_C2CStrong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).C2CStrong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_C2CStrong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).C2CStrong(ctx, req.(*C2CReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_C2CFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).C2CFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_C2CFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).C2CFinal(ctx, req.(*C2CReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountMgr_ServiceDesc is the grpc.ServiceDesc for AccountMgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountMgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account_mgr.AccountMgr",
	HandlerType: (*AccountMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bank2C",
			Handler:    _AccountMgr_Bank2C_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _AccountMgr_CreateAccount_Handler,
		},
		{
			MethodName: "GetUserBalanceInfo",
			Handler:    _AccountMgr_GetUserBalanceInfo_Handler,
		},
		{
			MethodName: "C2cLocal",
			Handler:    _AccountMgr_C2CLocal_Handler,
		},
		{
			MethodName: "C2cStrong",
			Handler:    _AccountMgr_C2CStrong_Handler,
		},
		{
			MethodName: "C2cFinal",
			Handler:    _AccountMgr_C2CFinal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_mgr.proto",
}
