// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: account_mgr.proto

package account_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建账户Req
type CreateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurType       int32                  `protobuf:"varint,3,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	mi := &file_account_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAccountReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

// 创建账户Rsp
type CreateAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRepeat      bool                   `protobuf:"varint,3,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRsp) Reset() {
	*x = CreateAccountRsp{}
	mi := &file_account_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRsp) ProtoMessage() {}

func (x *CreateAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRsp.ProtoReflect.Descriptor instead.
func (*CreateAccountRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAccountRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRsp) GetIsRepeat() bool {
	if x != nil {
		return x.IsRepeat
	}
	return false
}

// 获取账户余额Req
type GetUserBalanceInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	QryMode       int32                  `protobuf:"varint,2,opt,name=qry_mode,json=qryMode,proto3" json:"qry_mode,omitempty"` // 1-查从库 2-查主库
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceInfoReq) Reset() {
	*x = GetUserBalanceInfoReq{}
	mi := &file_account_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceInfoReq) ProtoMessage() {}

func (x *GetUserBalanceInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceInfoReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceInfoReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserBalanceInfoReq) GetQryMode() int32 {
	if x != nil {
		return x.QryMode
	}
	return 0
}

// 获取账户余额Rsp
type GetUserBalanceInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CurType       int32                  `protobuf:"varint,4,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceInfoRsp) Reset() {
	*x = GetUserBalanceInfoRsp{}
	mi := &file_account_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceInfoRsp) ProtoMessage() {}

func (x *GetUserBalanceInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserBalanceInfoRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceInfoRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserBalanceInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBalanceInfoRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetUserBalanceInfoRsp) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

// 获取账户流水Req
type GetUserFlowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 限制数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFlowReq) Reset() {
	*x = GetUserFlowReq{}
	mi := &file_account_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFlowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFlowReq) ProtoMessage() {}

func (x *GetUserFlowReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFlowReq.ProtoReflect.Descriptor instead.
func (*GetUserFlowReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserFlowReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserFlowReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUserFlowReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取账户流水Rsp
type GetUserFlowRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NextOffset    int32                  `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"` // 下一页偏移量
	EndFlag       int32                  `protobuf:"varint,4,opt,name=end_flag,json=endFlag,proto3" json:"end_flag,omitempty"`          // 是否是最后一页
	UserFlowList  []*UserFlow            `protobuf:"bytes,5,rep,name=UserFlowList,proto3" json:"UserFlowList,omitempty"`                // 账户流水列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFlowRsp) Reset() {
	*x = GetUserFlowRsp{}
	mi := &file_account_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFlowRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFlowRsp) ProtoMessage() {}

func (x *GetUserFlowRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFlowRsp.ProtoReflect.Descriptor instead.
func (*GetUserFlowRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserFlowRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserFlowRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFlowRsp) GetNextOffset() int32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *GetUserFlowRsp) GetEndFlag() int32 {
	if x != nil {
		return x.EndFlag
	}
	return 0
}

func (x *GetUserFlowRsp) GetUserFlowList() []*UserFlow {
	if x != nil {
		return x.UserFlowList
	}
	return nil
}

type UserFlow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CounterpartyUserId string                 `protobuf:"bytes,3,opt,name=counterparty_user_id,json=counterpartyUserId,proto3" json:"counterparty_user_id,omitempty"`
	InoutType          int32                  `protobuf:"varint,4,opt,name=inout_type,json=inoutType,proto3" json:"inout_type,omitempty"`
	BizType            int32                  `protobuf:"varint,5,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	Balance            int64                  `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Amount             int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc               string                 `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateTime         string                 `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserFlow) Reset() {
	*x = UserFlow{}
	mi := &file_account_mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFlow) ProtoMessage() {}

func (x *UserFlow) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFlow.ProtoReflect.Descriptor instead.
func (*UserFlow) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{6}
}

func (x *UserFlow) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UserFlow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFlow) GetCounterpartyUserId() string {
	if x != nil {
		return x.CounterpartyUserId
	}
	return ""
}

func (x *UserFlow) GetInoutType() int32 {
	if x != nil {
		return x.InoutType
	}
	return 0
}

func (x *UserFlow) GetBizType() int32 {
	if x != nil {
		return x.BizType
	}
	return 0
}

func (x *UserFlow) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserFlow) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserFlow) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UserFlow) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type GetC2CBillReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetC2CBillReq) Reset() {
	*x = GetC2CBillReq{}
	mi := &file_account_mgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetC2CBillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetC2CBillReq) ProtoMessage() {}

func (x *GetC2CBillReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetC2CBillReq.ProtoReflect.Descriptor instead.
func (*GetC2CBillReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{7}
}

func (x *GetC2CBillReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetC2CBillRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUid      int64                  `protobuf:"varint,2,opt,name=buyer_uid,json=buyerUid,proto3" json:"buyer_uid,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUid     int64                  `protobuf:"varint,4,opt,name=seller_uid,json=sellerUid,proto3" json:"seller_uid,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,5,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	PayTime       string                 `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	Amount        int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc          string                 `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetC2CBillRsp) Reset() {
	*x = GetC2CBillRsp{}
	mi := &file_account_mgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetC2CBillRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetC2CBillRsp) ProtoMessage() {}

func (x *GetC2CBillRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetC2CBillRsp.ProtoReflect.Descriptor instead.
func (*GetC2CBillRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{8}
}

func (x *GetC2CBillRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetC2CBillRsp) GetBuyerUid() int64 {
	if x != nil {
		return x.BuyerUid
	}
	return 0
}

func (x *GetC2CBillRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *GetC2CBillRsp) GetSellerUid() int64 {
	if x != nil {
		return x.SellerUid
	}
	return 0
}

func (x *GetC2CBillRsp) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *GetC2CBillRsp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *GetC2CBillRsp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetC2CBillRsp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Bank2CReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	BankType      int32                  `protobuf:"varint,4,opt,name=bank_type,json=bankType,proto3" json:"bank_type,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CurType       int32                  `protobuf:"varint,6,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	Desc          string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank2CReq) Reset() {
	*x = Bank2CReq{}
	mi := &file_account_mgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank2CReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank2CReq) ProtoMessage() {}

func (x *Bank2CReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank2CReq.ProtoReflect.Descriptor instead.
func (*Bank2CReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{9}
}

func (x *Bank2CReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Bank2CReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bank2CReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Bank2CReq) GetBankType() int32 {
	if x != nil {
		return x.BankType
	}
	return 0
}

func (x *Bank2CReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bank2CReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

func (x *Bank2CReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Bank2CRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank2CRsp) Reset() {
	*x = Bank2CRsp{}
	mi := &file_account_mgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank2CRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank2CRsp) ProtoMessage() {}

func (x *Bank2CRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank2CRsp.ProtoReflect.Descriptor instead.
func (*Bank2CRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{10}
}

func (x *Bank2CRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Bank2CRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type C2BankReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	BankType      int32                  `protobuf:"varint,4,opt,name=bank_type,json=bankType,proto3" json:"bank_type,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CurType       int32                  `protobuf:"varint,6,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	Desc          string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BankReq) Reset() {
	*x = C2BankReq{}
	mi := &file_account_mgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BankReq) ProtoMessage() {}

func (x *C2BankReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BankReq.ProtoReflect.Descriptor instead.
func (*C2BankReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{11}
}

func (x *C2BankReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2BankReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *C2BankReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *C2BankReq) GetBankType() int32 {
	if x != nil {
		return x.BankType
	}
	return 0
}

func (x *C2BankReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2BankReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

func (x *C2BankReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type C2BankRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BankRsp) Reset() {
	*x = C2BankRsp{}
	mi := &file_account_mgr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BankRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BankRsp) ProtoMessage() {}

func (x *C2BankRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BankRsp.ProtoReflect.Descriptor instead.
func (*C2BankRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{12}
}

func (x *C2BankRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2BankRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 转账Req
type C2CReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUid      int64                  `protobuf:"varint,2,opt,name=buyer_uid,json=buyerUid,proto3" json:"buyer_uid,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUid     int64                  `protobuf:"varint,4,opt,name=seller_uid,json=sellerUid,proto3" json:"seller_uid,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,5,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	CurType       int32                  `protobuf:"varint,7,opt,name=cur_type,json=curType,proto3" json:"cur_type,omitempty"`
	Desc          string                 `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CReq) Reset() {
	*x = C2CReq{}
	mi := &file_account_mgr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CReq) ProtoMessage() {}

func (x *C2CReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CReq.ProtoReflect.Descriptor instead.
func (*C2CReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{13}
}

func (x *C2CReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2CReq) GetBuyerUid() int64 {
	if x != nil {
		return x.BuyerUid
	}
	return 0
}

func (x *C2CReq) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CReq) GetSellerUid() int64 {
	if x != nil {
		return x.SellerUid
	}
	return 0
}

func (x *C2CReq) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2CReq) GetCurType() int32 {
	if x != nil {
		return x.CurType
	}
	return 0
}

func (x *C2CReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// 转账Rsp
type C2CRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BuyerUid      int64                  `protobuf:"varint,2,opt,name=buyer_uid,json=buyerUid,proto3" json:"buyer_uid,omitempty"`
	BuyerUserId   string                 `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	SellerUid     int64                  `protobuf:"varint,4,opt,name=seller_uid,json=sellerUid,proto3" json:"seller_uid,omitempty"`
	SellerUserId  string                 `protobuf:"bytes,5,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	PayTime       string                 `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,7,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CRsp) Reset() {
	*x = C2CRsp{}
	mi := &file_account_mgr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CRsp) ProtoMessage() {}

func (x *C2CRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CRsp.ProtoReflect.Descriptor instead.
func (*C2CRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{14}
}

func (x *C2CRsp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *C2CRsp) GetBuyerUid() int64 {
	if x != nil {
		return x.BuyerUid
	}
	return 0
}

func (x *C2CRsp) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *C2CRsp) GetSellerUid() int64 {
	if x != nil {
		return x.SellerUid
	}
	return 0
}

func (x *C2CRsp) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *C2CRsp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *C2CRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

type C2CAsyncAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CAsyncAccountReq) Reset() {
	*x = C2CAsyncAccountReq{}
	mi := &file_account_mgr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CAsyncAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CAsyncAccountReq) ProtoMessage() {}

func (x *C2CAsyncAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CAsyncAccountReq.ProtoReflect.Descriptor instead.
func (*C2CAsyncAccountReq) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{15}
}

func (x *C2CAsyncAccountReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type C2CAsyncAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CAsyncAccountRsp) Reset() {
	*x = C2CAsyncAccountRsp{}
	mi := &file_account_mgr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CAsyncAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CAsyncAccountRsp) ProtoMessage() {}

func (x *C2CAsyncAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_account_mgr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CAsyncAccountRsp.ProtoReflect.Descriptor instead.
func (*C2CAsyncAccountRsp) Descriptor() ([]byte, []int) {
	return file_account_mgr_proto_rawDescGZIP(), []int{16}
}

var File_account_mgr_proto protoreflect.FileDescriptor

const file_account_mgr_proto_rawDesc = "" +
	"\n" +
	"\x11account_mgr.proto\x12\vaccount_mgr\"X\n" +
	"\x10CreateAccountReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bcur_type\x18\x03 \x01(\x05R\acurType\"Z\n" +
	"\x10CreateAccountRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_repeat\x18\x03 \x01(\bR\bisRepeat\"D\n" +
	"\x15GetUserBalanceInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\bqry_mode\x18\x02 \x01(\x05R\aqryMode\"w\n" +
	"\x15GetUserBalanceInfoRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x19\n" +
	"\bcur_type\x18\x04 \x01(\x05R\acurType\"P\n" +
	"\x0eGetUserFlowReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb2\x01\n" +
	"\x0eGetUserFlowRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\x05R\n" +
	"nextOffset\x12\x19\n" +
	"\bend_flag\x18\x04 \x01(\x05R\aendFlag\x129\n" +
	"\fUserFlowList\x18\x05 \x03(\v2\x15.account_mgr.UserFlowR\fUserFlowList\"\x9d\x02\n" +
	"\bUserFlow\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x120\n" +
	"\x14counterparty_user_id\x18\x03 \x01(\tR\x12counterpartyUserId\x12\x1d\n" +
	"\n" +
	"inout_type\x18\x04 \x01(\x05R\tinoutType\x12\x19\n" +
	"\bbiz_type\x18\x05 \x01(\x05R\abizType\x12\x18\n" +
	"\abalance\x18\a \x01(\x03R\abalance\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04desc\x18\b \x01(\tR\x04desc\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\tR\n" +
	"createTime\"6\n" +
	"\rGetC2CBillReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x83\x02\n" +
	"\rGetC2CBillRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tbuyer_uid\x18\x02 \x01(\x03R\bbuyerUid\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12\x1d\n" +
	"\n" +
	"seller_uid\x18\x04 \x01(\x03R\tsellerUid\x12$\n" +
	"\x0eseller_user_id\x18\x05 \x01(\tR\fsellerUserId\x12\x19\n" +
	"\bpay_time\x18\x06 \x01(\tR\apayTime\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x12\n" +
	"\x04desc\x18\b \x01(\tR\x04desc\"\xc1\x01\n" +
	"\tBank2CReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tbank_type\x18\x04 \x01(\x05R\bbankType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x19\n" +
	"\bcur_type\x18\x06 \x01(\x05R\acurType\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\"K\n" +
	"\tBank2CRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xc1\x01\n" +
	"\tC2BankReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tbank_type\x18\x04 \x01(\x05R\bbankType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x19\n" +
	"\bcur_type\x18\x06 \x01(\x05R\acurType\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\"K\n" +
	"\tC2BankRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xfc\x01\n" +
	"\x06C2CReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tbuyer_uid\x18\x02 \x01(\x03R\bbuyerUid\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12\x1d\n" +
	"\n" +
	"seller_uid\x18\x04 \x01(\x03R\tsellerUid\x12$\n" +
	"\x0eseller_user_id\x18\x05 \x01(\tR\fsellerUserId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x19\n" +
	"\bcur_type\x18\a \x01(\x05R\acurType\x12\x12\n" +
	"\x04desc\x18\b \x01(\tR\x04desc\"\xed\x01\n" +
	"\x06C2CRsp\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tbuyer_uid\x18\x02 \x01(\x03R\bbuyerUid\x12\"\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tR\vbuyerUserId\x12\x1d\n" +
	"\n" +
	"seller_uid\x18\x04 \x01(\x03R\tsellerUid\x12$\n" +
	"\x0eseller_user_id\x18\x05 \x01(\tR\fsellerUserId\x12\x19\n" +
	"\bpay_time\x18\x06 \x01(\tR\apayTime\x12\x1b\n" +
	"\tis_repeat\x18\a \x01(\x05R\bisRepeat\";\n" +
	"\x12C2CAsyncAccountReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x14\n" +
	"\x12C2CAsyncAccountRsp2\xfd\x04\n" +
	"\n" +
	"AccountMgr\x12M\n" +
	"\rCreateAccount\x12\x1d.account_mgr.CreateAccountReq\x1a\x1d.account_mgr.CreateAccountRsp\x12\\\n" +
	"\x12GetUserBalanceInfo\x12\".account_mgr.GetUserBalanceInfoReq\x1a\".account_mgr.GetUserBalanceInfoRsp\x12G\n" +
	"\vGetUserFlow\x12\x1b.account_mgr.GetUserFlowReq\x1a\x1b.account_mgr.GetUserFlowRsp\x12D\n" +
	"\n" +
	"GetC2CBill\x12\x1a.account_mgr.GetC2CBillReq\x1a\x1a.account_mgr.GetC2CBillRsp\x128\n" +
	"\x06Bank2C\x12\x16.account_mgr.Bank2CReq\x1a\x16.account_mgr.Bank2CRsp\x128\n" +
	"\x06C2Bank\x12\x16.account_mgr.C2BankReq\x1a\x16.account_mgr.C2BankRsp\x124\n" +
	"\bC2CLocal\x12\x13.account_mgr.C2CReq\x1a\x13.account_mgr.C2CRsp\x124\n" +
	"\bC2CFinal\x12\x13.account_mgr.C2CReq\x1a\x13.account_mgr.C2CRsp\x12S\n" +
	"\x0fC2CAsyncAccount\x12\x1f.account_mgr.C2CAsyncAccountReq\x1a\x1f.account_mgr.C2CAsyncAccountRspB\x12Z\x10./account_mgr_pbb\x06proto3"

var (
	file_account_mgr_proto_rawDescOnce sync.Once
	file_account_mgr_proto_rawDescData []byte
)

func file_account_mgr_proto_rawDescGZIP() []byte {
	file_account_mgr_proto_rawDescOnce.Do(func() {
		file_account_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_mgr_proto_rawDesc), len(file_account_mgr_proto_rawDesc)))
	})
	return file_account_mgr_proto_rawDescData
}

var file_account_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_account_mgr_proto_goTypes = []any{
	(*CreateAccountReq)(nil),      // 0: account_mgr.CreateAccountReq
	(*CreateAccountRsp)(nil),      // 1: account_mgr.CreateAccountRsp
	(*GetUserBalanceInfoReq)(nil), // 2: account_mgr.GetUserBalanceInfoReq
	(*GetUserBalanceInfoRsp)(nil), // 3: account_mgr.GetUserBalanceInfoRsp
	(*GetUserFlowReq)(nil),        // 4: account_mgr.GetUserFlowReq
	(*GetUserFlowRsp)(nil),        // 5: account_mgr.GetUserFlowRsp
	(*UserFlow)(nil),              // 6: account_mgr.UserFlow
	(*GetC2CBillReq)(nil),         // 7: account_mgr.GetC2CBillReq
	(*GetC2CBillRsp)(nil),         // 8: account_mgr.GetC2CBillRsp
	(*Bank2CReq)(nil),             // 9: account_mgr.Bank2CReq
	(*Bank2CRsp)(nil),             // 10: account_mgr.Bank2CRsp
	(*C2BankReq)(nil),             // 11: account_mgr.C2BankReq
	(*C2BankRsp)(nil),             // 12: account_mgr.C2BankRsp
	(*C2CReq)(nil),                // 13: account_mgr.C2CReq
	(*C2CRsp)(nil),                // 14: account_mgr.C2CRsp
	(*C2CAsyncAccountReq)(nil),    // 15: account_mgr.C2CAsyncAccountReq
	(*C2CAsyncAccountRsp)(nil),    // 16: account_mgr.C2CAsyncAccountRsp
}
var file_account_mgr_proto_depIdxs = []int32{
	6,  // 0: account_mgr.GetUserFlowRsp.UserFlowList:type_name -> account_mgr.UserFlow
	0,  // 1: account_mgr.AccountMgr.CreateAccount:input_type -> account_mgr.CreateAccountReq
	2,  // 2: account_mgr.AccountMgr.GetUserBalanceInfo:input_type -> account_mgr.GetUserBalanceInfoReq
	4,  // 3: account_mgr.AccountMgr.GetUserFlow:input_type -> account_mgr.GetUserFlowReq
	7,  // 4: account_mgr.AccountMgr.GetC2CBill:input_type -> account_mgr.GetC2CBillReq
	9,  // 5: account_mgr.AccountMgr.Bank2C:input_type -> account_mgr.Bank2CReq
	11, // 6: account_mgr.AccountMgr.C2Bank:input_type -> account_mgr.C2BankReq
	13, // 7: account_mgr.AccountMgr.C2CLocal:input_type -> account_mgr.C2CReq
	13, // 8: account_mgr.AccountMgr.C2CFinal:input_type -> account_mgr.C2CReq
	15, // 9: account_mgr.AccountMgr.C2CAsyncAccount:input_type -> account_mgr.C2CAsyncAccountReq
	1,  // 10: account_mgr.AccountMgr.CreateAccount:output_type -> account_mgr.CreateAccountRsp
	3,  // 11: account_mgr.AccountMgr.GetUserBalanceInfo:output_type -> account_mgr.GetUserBalanceInfoRsp
	5,  // 12: account_mgr.AccountMgr.GetUserFlow:output_type -> account_mgr.GetUserFlowRsp
	8,  // 13: account_mgr.AccountMgr.GetC2CBill:output_type -> account_mgr.GetC2CBillRsp
	10, // 14: account_mgr.AccountMgr.Bank2C:output_type -> account_mgr.Bank2CRsp
	12, // 15: account_mgr.AccountMgr.C2Bank:output_type -> account_mgr.C2BankRsp
	14, // 16: account_mgr.AccountMgr.C2CLocal:output_type -> account_mgr.C2CRsp
	14, // 17: account_mgr.AccountMgr.C2CFinal:output_type -> account_mgr.C2CRsp
	16, // 18: account_mgr.AccountMgr.C2CAsyncAccount:output_type -> account_mgr.C2CAsyncAccountRsp
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_account_mgr_proto_init() }
func file_account_mgr_proto_init() {
	if File_account_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_mgr_proto_rawDesc), len(file_account_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_mgr_proto_goTypes,
		DependencyIndexes: file_account_mgr_proto_depIdxs,
		MessageInfos:      file_account_mgr_proto_msgTypes,
	}.Build()
	File_account_mgr_proto = out.File
	file_account_mgr_proto_goTypes = nil
	file_account_mgr_proto_depIdxs = nil
}
