// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: account_mgr.proto

package account_mgr_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountMgr_CreateAccount_FullMethodName  = "/account_mgr.AccountMgr/CreateAccount"
	AccountMgr_GetBalanceInfo_FullMethodName = "/account_mgr.AccountMgr/GetBalanceInfo"
	AccountMgr_C2CTransfer_FullMethodName    = "/account_mgr.AccountMgr/C2cTransfer"
)

// AccountMgrClient is the client API for AccountMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountMgrClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error)
	GetBalanceInfo(ctx context.Context, in *GetBalanceInfoReq, opts ...grpc.CallOption) (*GetBalanceInfoRsp, error)
	C2CTransfer(ctx context.Context, in *C2CTransferReq, opts ...grpc.CallOption) (*C2CTransferRsp, error)
}

type accountMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountMgrClient(cc grpc.ClientConnInterface) AccountMgrClient {
	return &accountMgrClient{cc}
}

func (c *accountMgrClient) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountRsp)
	err := c.cc.Invoke(ctx, AccountMgr_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) GetBalanceInfo(ctx context.Context, in *GetBalanceInfoReq, opts ...grpc.CallOption) (*GetBalanceInfoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceInfoRsp)
	err := c.cc.Invoke(ctx, AccountMgr_GetBalanceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountMgrClient) C2CTransfer(ctx context.Context, in *C2CTransferReq, opts ...grpc.CallOption) (*C2CTransferRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2CTransferRsp)
	err := c.cc.Invoke(ctx, AccountMgr_C2CTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountMgrServer is the server API for AccountMgr service.
// All implementations must embed UnimplementedAccountMgrServer
// for forward compatibility.
type AccountMgrServer interface {
	CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountRsp, error)
	GetBalanceInfo(context.Context, *GetBalanceInfoReq) (*GetBalanceInfoRsp, error)
	C2CTransfer(context.Context, *C2CTransferReq) (*C2CTransferRsp, error)
	mustEmbedUnimplementedAccountMgrServer()
}

// UnimplementedAccountMgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountMgrServer struct{}

func (UnimplementedAccountMgrServer) CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountMgrServer) GetBalanceInfo(context.Context, *GetBalanceInfoReq) (*GetBalanceInfoRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceInfo not implemented")
}
func (UnimplementedAccountMgrServer) C2CTransfer(context.Context, *C2CTransferReq) (*C2CTransferRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method C2CTransfer not implemented")
}
func (UnimplementedAccountMgrServer) mustEmbedUnimplementedAccountMgrServer() {}
func (UnimplementedAccountMgrServer) testEmbeddedByValue()                    {}

// UnsafeAccountMgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountMgrServer will
// result in compilation errors.
type UnsafeAccountMgrServer interface {
	mustEmbedUnimplementedAccountMgrServer()
}

func RegisterAccountMgrServer(s grpc.ServiceRegistrar, srv AccountMgrServer) {
	// If the following call panics, it indicates UnimplementedAccountMgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountMgr_ServiceDesc, srv)
}

func _AccountMgr_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).CreateAccount(ctx, req.(*CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_GetBalanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).GetBalanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_GetBalanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).GetBalanceInfo(ctx, req.(*GetBalanceInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountMgr_C2CTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountMgrServer).C2CTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountMgr_C2CTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountMgrServer).C2CTransfer(ctx, req.(*C2CTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountMgr_ServiceDesc is the grpc.ServiceDesc for AccountMgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountMgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account_mgr.AccountMgr",
	HandlerType: (*AccountMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountMgr_CreateAccount_Handler,
		},
		{
			MethodName: "GetBalanceInfo",
			Handler:    _AccountMgr_GetBalanceInfo_Handler,
		},
		{
			MethodName: "C2cTransfer",
			Handler:    _AccountMgr_C2CTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_mgr.proto",
}
